openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /estate:
    post:
      summary: Creates and stores a new estate in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstateRequest"
      responses:
        "201":
          description: Successful creation of the estate.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstateResponse"
        "400":
          description: Invalid value or format received.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /estate/{id}/tree:
    post:
      summary: Store tree data in a given estate
      parameters:
        - $ref: "#/components/parameters/EstateIDPathParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TreeRequest"
      responses:
        "201":
          description: Successful add tree to estate.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TreeResponse"
        "400":
          description: Invalid value or format received.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: State not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /estate/{id}/stats:
    get:
      summary: Retrieve stats of trees in a given estate.
      parameters:
        - $ref: "#/components/parameters/EstateIDPathParam"
      responses:
        "200":
          description: Stats of the trees in the estate.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstateStatsResponse"
        "404":
          description: Estate not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  parameters:
    EstateIDPathParam:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: ID of the estate where the tree will be stored

  schemas:
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    EstateRequest:
      type: object
      required:
        - length
        - width
      properties:
        width:
          type: integer
          minimum: 1
          maximum: 50000
        length:
          type: integer
          minimum: 1
          maximum: 50000
    EstateResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    TreeRequest:
      type: object
      required:
        - x
        - y
        - height
      properties:
        x:
          type: integer
          minimum: 1
          maximum: 50000
        y:
          type: integer
          minimum: 1
          maximum: 50000
        height:
          type: integer
          minimum: 1
          maximum: 30
    TreeResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    EstateStatsResponse:
      type: object
      required:
        - count
        - max
        - min
        - median
      properties:
        count:
          type: integer
        max:
          type: integer
        min:
          type: integer
        median:
          type: integer
